#!/bin/sh

mkdir -p checkout
cd checkout

echo "Checking out libccp4"
bzr branch http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/libccp4/trunk/ libccp4
echo
echo "Checking out clipper"
bzr branch http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/clipper/trunk/ clipper
echo
echo "Checking out ssm"
bzr branch http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/ssm/trunk/ ssm
echo
echo "Checking out mmdb2"
bzr branch http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/mmdb2/trunk/ mmdb2
echo
echo "Checking out ccp4srs"
bzr branch http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/ccp4srs/trunk/ ccp4srs
echo
echo "Checking out rvapi"
bzr branch http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/rvapi/trunk/ rvapi
echo
echo "Checking out gesamt"
bzr branch http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/gesamt/trunk/ gesamt
echo
echo "Checking out gemmi"
git clone https://github.com/project-gemmi/gemmi.git gemmi
echo
echo "Checking out ccp4mg"
bzr branch http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/ccp4mg/ccp4-pyside2-opengl33/ ccp4mg
echo
echo "Checking out prosmart"
bzr branch http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/prosmart/trunk prosmart
echo
echo "Checking out monomers"
bzr branch http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/monomers/trunk/ monomers
echo

echo "Downloading privateer MKIV"
curl -L https://github.com/agirre/privateer/archive/refs/tags/MKIV.tar.gz -o privateer-MKIV.tar.gz
echo
echo "Downloading out fftw-2.1.5"
curl -L http://www.fftw.org/fftw-2.1.5.tar.gz -o fftw-2.1.5.tar.gz
echo
echo "Downloading gsl-2.7.1"
curl -L https://mirror.ibcp.fr/pub/gnu/gsl/gsl-2.7.1.tar.gz -o gsl-2.7.1.tar.gz
echo
echo "Downloading coot-0.9.6"
curl -L https://www2.mrc-lmb.cam.ac.uk/personal/pemsley/coot/source/releases/coot-0.9.6.tar.gz -o coot-0.9.6.tar.gz
echo

echo "Unpacking privateer MKIV"
tar xf privateer-MKIV.tar.gz
echo "Unpacking out fftw-2.1.5"
tar xf fftw-2.1.5.tar.gz
echo "Unpacking coot-0.9.6"
tar xf coot-0.9.6.tar.gz

patch -p0 < ../patches/ccp4-emscripten.patch 
patch -p0 < ../patches/privateer-nopybind.patch
patch -p0 < ../patches/superpose-emscripten.patch
patch -p0 < ../patches/gesamt-emscripten.patch
patch -p0 < ../patches/privateer-emscripten.patch
patch -p0 < ../patches/coot-fixnomenclature.patch
patch -p0 < ../patches/coot-getopt.patch
patch -p0 < ../patches/coot-mini-rsr.patch
cd ..
echo
echo "Unpacking gsl-2.7.1"
tar xf checkout/gsl-2.7.1.tar.gz
echo

#Create an empty file silly.c and then compile it with USE_ZLIB to force emsdk to get zlib.
echo "Attempting to get emsdk zlib port"
echo
echo "" > silly.c
emcc silly.c -s USE_ZLIB=1
rm -f silly.c

#Get RDKit
echo "Downloading RDKit_minimal js/wasm"
echo
curl -L https://unpkg.com/@rdkit/rdkit/Code/MinimalLib/dist/RDKit_minimal.wasm -o web_example/RDKit_minimal.wasm
curl -L https://unpkg.com/@rdkit/rdkit/Code/MinimalLib/dist/RDKit_minimal.js -o web_example/RDKit_minimal.js

#Get PapaParse
echo "Downloading papaparse.min.js"
echo
curl -L https://unpkg.com/papaparse@latest/papaparse.min.js -o web_example/papaparse.min.js

#Get Chart.Js
echo "Downloading chart.js"
echo
curl -L https://cdn.jsdelivr.net/npm/chart.js -o web_example/chart.js

#Get example data
echo "Downloading example data"
echo
curl -L https://www.ebi.ac.uk/pdbe/entry-files/download/pdb1df7.ent -o example/1df7.pdb
curl -L https://www.ebi.ac.uk/pdbe/entry-files/download/pdb4dfr.ent -o example/4dfr.pdb
curl -L https://www.ebi.ac.uk/pdbe/entry-files/download/pdb8dfr.ent -o example/8dfr.pdb
curl -L https://www.ebi.ac.uk/pdbe/entry-files/download/pdb5a3h.ent -o example/5a3h.pdb
curl -L https://www.ebi.ac.uk/pdbe/entry-files/download/pdb5fjj.ent -o privateer/5fjj.pdb
curl -L https://www.ebi.ac.uk/pdbe/entry-files/download/r5a3hsf.ent -o example/r5a3hsf.ent
curl -L https://www.ebi.ac.uk/pdbe/entry-files/download/5a3h_map.mtz -o example/5a3h_sigmaa.mtz

#Get react dependencies
echo "Getting react app dependencies"
echo
cd react-app
npm install
