#!/bin/sh

mkdir -p checkout
cd checkout

bzr branch http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/libccp4/trunk/ libccp4
bzr branch http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/clipper/trunk/ clipper
bzr branch http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/ssm/trunk/ ssm
bzr branch http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/mmdb2/trunk/ mmdb2
bzr branch http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/ccp4srs/trunk/ ccp4srs
git clone https://github.com/project-gemmi/gemmi.git gemmi

curl -L https://github.com/agirre/privateer/archive/refs/tags/MKIV.tar.gz -o privateer-MKIV.tar.gz
curl -L http://www.fftw.org/fftw-2.1.5.tar.gz -o fftw-2.1.5.tar.gz
curl -L https://mirror.ibcp.fr/pub/gnu/gsl/gsl-2.7.1.tar.gz -o gsl-2.7.1.tar.gz
curl -L https://www2.mrc-lmb.cam.ac.uk/personal/pemsley/coot/source/releases/coot-0.9.6.tar.gz -o coot-0.9.6.tar.gz
tar xf privateer-MKIV.tar.gz
tar xf fftw-2.1.5.tar.gz
tar xf checkout/coot-0.9.6.tar.gz

patch -p0 < ../patches/ccp4-emscripten.patch 
patch -p0 < ../patches/privateer-nopybind.patch
cd ..
tar xf checkout/gsl-2.7.1.tar.gz

#Create an empty file silly.c and then compile it with USE_ZLIB to force emsdk to get zlib.
echo "Attempting to get emsdk zlib port."
echo "" > silly.c
emcc silly.c -s USE_ZLIB=1
rm -f silly.c
