#!/bin/sh

if [ "x$MOORHEN_SOURCE_DIR" = "x" ]; then
    if command -v greadlink > /dev/null 2>&1; then
        MOORHEN_SOURCE_DIR=`dirname -- "$( greadlink -f -- "$0"; )"`
    else
        MOORHEN_SOURCE_DIR=`dirname -- "$( readlink -f -- "$0"; )"`
    fi
else
    echo "Using MOORHEN_SOURCE_DIR from environment: $MOORHEN_SOURCE_DIR"
fi

. ${MOORHEN_SOURCE_DIR}/VERSIONS

fail() {
    echo $1
    exit 1
}

cdcheckout() {
    mkdir -p ${MOORHEN_SOURCE_DIR}/checkout &&\
    cd ${MOORHEN_SOURCE_DIR}/checkout || fail "Failed to cd to checkout directory"
}

geteigen() {
    cdcheckout
    if [ -r eigen-$libeigen_release ]; then
        echo "Using existing LibEigen"
    else
        echo "Checking out LibEigen"
        curl -fL https://gitlab.com/libeigen/eigen/-/archive/$libeigen_release/eigen-$libeigen_release.tar.gz -o eigen-$libeigen_release.tar.gz &&\
        tar xf eigen-$libeigen_release.tar.gz || fail "Failed to download and unpack LibEigen"
    fi
    echo
}

getlibccp4() {
    cdcheckout
    if [ -r libccp4-$libccp4_release ]; then
        echo "Using existing libccp4"
    else
        echo "Checking out libccp4"
        curl -fL https://ftp.ccp4.ac.uk/opensource/libccp4-$libccp4_release.tar.gz -o libccp4-$libccp4_release.tar.gz &&\
        echo &&\
        echo "Unpacking libccp4 source" &&\
        tar xf libccp4-$libccp4_release.tar.gz &&\
        ln -s libccp4-$libccp4_release libccp4 &&\
        echo &&\
        echo "Patching libccp4 for Emscripten" &&\
        patch -p0 < ../patches/ccp4-emscripten.patch &&\
        cd .. || fail "Failed to download, unpack and patch libccp4"
    fi
    echo
}

getclipper() {
    cdcheckout
    if [ -r clipper ]; then
        echo "Using existing clipper"
    else
        echo "Checking out clipper (gemmi branch)"
        git clone -b gemmi https://ccp4forge.rc-harwell.ac.uk/ccp4/clipper.git || fail "Failed to clone clipper"
        echo
    fi
    echo
}

getssm() {
    cdcheckout
    if [ -r ssm-$ssm_release ]; then
        echo "Using existing ssm"
    else
        echo "Checking out ssm"
        curl https://ftp.ccp4.ac.uk/opensource/ssm-$ssm_release.tar.gz -o ssm-$ssm_release.tar.gz &&\
        echo &&\
        echo "Unpacking ssm source" &&\
        tar xf ssm-$ssm_release.tar.gz || fail "Failed to download and unpack ssm"
        rm -f ssm
        ln -s ssm-$ssm_release ssm
    fi
    echo
}

getmmdb2() {
    cdcheckout
    if [ -r mmdb2-$mmdb_release ]; then
        echo "Using existing mmdb2"
    else
        echo "Checking out mmdb2"
        curl -fL https://ftp.ccp4.ac.uk/opensource/mmdb2-$mmdb_release.tar.gz -o mmdb2-$mmdb_release.tar.gz &&\
        echo &&\
        echo "Unpacking mmdb2 source" &&\
        tar xf mmdb2-$mmdb_release.tar.gz &&\
        rm -f mmdb2 &&\
        ln -s mmdb2-$mmdb_release mmdb2 &&\
        patch -p0 < ../patches/mmdb-emsdk500.patch || fail "Failed to download, unpack and patch mmdb2"
    fi
    echo
}

getgemmi() {
    cdcheckout
    if [ -r gemmi ]; then
        echo "Using existing gemmi"
    else
        echo "Checking out gemmi"
        git clone https://github.com/project-gemmi/gemmi.git gemmi &&\
        cd gemmi &&\
        git checkout $gemmi_release &&\
        patch -p1 < ../../patches/gemmi-emscripten-64.patch || fail "Failed to clone and patch gemmi"
    fi
    echo
}

getmonomers() {
    cdcheckout
    if [ -r monomers/list/mon_lib_list.cif ]; then
        echo "Using existing monomers"
    else
        echo "Checking out monomers subset"
        #git clone https://github.com/MonomerLibrary/monomers monomers
        mkdir -p monomers/a monomers/c monomers/e monomers/g monomers/h monomers/i monomers/l monomers/m monomers/p monomers/s monomers/t monomers/v monomers/u monomers/d monomers/h monomers/n monomers/h monomers/list &&\
        cd monomers &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/a/ALA.cif -o a/ALA.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/a/ASP.cif -o a/ASP.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/a/ASN.cif -o a/ASN.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/a/ARG.cif -o a/ARG.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/c/CYS.cif -o c/CYS.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/c/CIT.cif -o c/CIT.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/e/EDO.cif -o e/EDO.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/g/GLN.cif -o g/GLN.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/g/GLY.cif -o g/GLY.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/g/GOL.cif -o g/GOL.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/g/GLU.cif -o g/GLU.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/h/HIS.cif -o h/HIS.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/i/ILE.cif -o i/ILE.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/l/LYS.cif -o l/LYS.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/l/LEU.cif -o l/LEU.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/m/MET.cif -o m/MET.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/m/MSE.cif -o m/MSE.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/p/PRO.cif -o p/PRO.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/p/PHE.cif -o p/PHE.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/p/PO4.cif -o p/PO4.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/p/PEG.cif -o p/PEG.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/s/SER.cif -o s/SER.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/s/SO4.cif -o s/SO4.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/t/THR.cif -o t/THR.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/t/TRP.cif -o t/TRP.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/t/TYR.cif -o t/TYR.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/v/VAL.cif -o v/VAL.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/a/A.cif -o a/A.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/c/C.cif -o c/C.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/g/G.cif -o g/G.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/u/U.cif -o u/U.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/d/DA.cif -o d/DA.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/d/DC.cif -o d/DC.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/d/DG.cif -o d/DG.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/d/DT.cif -o d/DT.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/h/HOH.cif -o h/HOH.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/n/NA.cif -o n/NA.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/a/ATP.cif -o a/ATP.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/a/ADP.cif -o a/ADP.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/ener_lib.cif -o ener_lib.cif &&\
        curl -fL https://raw.githubusercontent.com/MonomerLibrary/monomers/refs/heads/master/list/mon_lib_list.cif -o list/mon_lib_list.cif || fail "Failed to download monomers"
    fi
    echo
}

getjsoncpp() {
    cdcheckout
    if [ -r jsoncpp ]; then
        echo "Using existing jsoncpp"
    else
        echo "Checking out jsoncpp"
        git clone https://github.com/open-source-parsers/jsoncpp.git &&\
        cd jsoncpp &&\
        git checkout $jsoncpp_release || fail "Failed to clone and checkout jsoncpp"
    fi
    echo
}

getigraph() {
    cdcheckout
    if [ -r igraph ]; then
        echo "Using existing igraph"
    else
        echo "Checking out igraph"
        git clone https://github.com/igraph/igraph.git || fail "Failed to clone igraph"
    fi
    echo
}

getslicendice() {
    cdcheckout
    if [ -r slicendice_cpp ]; then
        echo "Using existing slicendice_cpp"
    else
        echo "Checking out SliceNDice"
        git clone https://github.com/hlasimpk/slicendice_cpp.git || fail "Failed to clone SliceNDice"
    fi
    echo
}

getconkit() {
    cdcheckout
    if [ -r conkit ]; then
        echo "Using existing conkit_cpp"
    else
        echo "Checking out ConKit Validate"
        git clone https://github.com/hlasimpk/conkit_validate_cpp.git conkit || fail "Failed to clone conkit"
    fi
    echo
}

getfftw() {
    cdcheckout
    if [ -r fftw-$fftw_release ]; then
        echo "Using existing fftw"
    else
        echo "Downloading out fftw-$fftw_release"
        curl -fL http://www.fftw.org/fftw-$fftw_release.tar.gz -o fftw-$fftw_release.tar.gz &&\
        echo &&\
        echo "Unpacking fftw-$fftw_release" &&\
        tar xf fftw-$fftw_release.tar.gz || fail "Failed to download and unpack fftw"
    fi
    echo
}

getfftw3() {
    cdcheckout
    if [ -r fftw-$fftw3_release ]; then
        echo "Using existing fftw3"
    else
        echo "Downloading out fftw-$fftw3_release"
        curl -fL http://www.fftw.org/fftw-$fftw3_release.tar.gz -o fftw-$fftw3_release.tar.gz &&\
        echo &&\
        echo "Unpacking fftw-$fftw3_release" &&\
        tar xf fftw-$fftw3_release.tar.gz || fail "Failed to download and unpack fftw3"
    fi
    echo
}

getfreetype() {
    cdcheckout
    if [ -r freetype-$freetype_release ]; then
        echo "Using existing freetype"
    else
        cdcheckout
        echo "Downloading freetype-$freetype_release"
        curl --retry 5 -fL https://download.savannah.gnu.org/releases/freetype/freetype-$freetype_release.tar.gz -o freetype-$freetype_release.tar.gz &&\
        echo &&\
        echo "Unpacking freetype-$freetype_release" &&\
        tar xf freetype-$freetype_release.tar.gz || fail "Failed to download and unpack freetype"
    fi
    echo
}

getpng() {
    cdcheckout
    if [ -r libpng-$png_release ]; then
        echo "Using existing png"
    else
        cdcheckout
        echo "Downloading png-$png_release"
        curl -fL http://prdownloads.sourceforge.net/libpng/libpng-$png_release.tar.gz -o libpng-$png_release.tar.gz &&\
        echo &&\
        echo "Unpacking png-$png_release" &&\
        tar xf libpng-$png_release.tar.gz || fail "Failed to download and unpack png"
    fi
    echo
}

getzlib() {
    cdcheckout
    if [ -r zlib-$zlib_release ]; then
        echo "Using existing zlib"
    else
        cdcheckout
        echo "Downloading zlib-$zlib_release"
        curl -fL https://www.zlib.net/zlib-$zlib_release.tar.gz -o zlib-$zlib_release.tar.gz &&\
        echo &&\
        echo "Unpacking zlib-$zlib_release" &&\
        tar xf zlib-$zlib_release.tar.gz || fail "Failed to download and unpack zlib"
    fi
    echo
}

getgsl() {
#FIXME This is mysteriously in top level!!!
    cd ${MOORHEN_SOURCE_DIR}
    if [ -r gsl-$gsl_release ]; then
        echo "Using existing gsl"
    else
        cdcheckout
        echo "Downloading gsl-$gsl_release"
        curl -fL https://ftp.gnu.org/gnu/gsl/gsl-$gsl_release.tar.gz -o gsl-$gsl_release.tar.gz &&\
        echo &&\
        cd ${MOORHEN_SOURCE_DIR} &&\
        echo "Unpacking gsl-$gsl_release" &&\
        tar xf checkout/gsl-$gsl_release.tar.gz || fail "Failed to download and unpack gsl"
    fi
    echo
}


getcoot() {
    cdcheckout
    if [ -r coot-1.0 ]; then
        if [ "x$(git -C coot-1.0 rev-parse --short=10 main)" = "x$coot_commit" ];then
            echo "Using existing coot-1.0"
        else
            echo "Checking-out existent coot-1.0 to a different version ($(git -C coot-1.0 rev-parse --short=10 main) -> $coot_commit)"
            git -C coot-1.0 fetch &&\
            git -C coot-1.0 checkout $coot_commit &&\
            echo Using checked-out coot-1.0 || fail "Failed to checkout coot-1.0"
        fi
    else
        echo "Downloading coot-1.0..."
        git clone --branch main https://github.com/pemsley/coot.git coot-1.0 &&\
        git -C coot-1.0 fetch origin &&\
        git -C coot-1.0 checkout $coot_commit || fail "Failed to clone and checkout coot-1.0"
    fi
    echo
}

getlhasa() {
    cdcheckout
    if [ -r LhasaReact ]; then
        if [ "x$(git -C LhasaReact rev-parse --short=10 main)" = "x$lhasa_commit" ];then
            echo "Using existing LhasaReact"
        else
            echo "Checking-out existent LhasaReact to a different version ($(git -C LhasaReact rev-parse --short=10 main) -> $lhasa_commit)"
            git -C LhasaReact fetch &&\
            git -C LhasaReact checkout $lhasa_commit &&\
            echo Using checked-out LhasaReact || fail "Failed to checkout LhasaReact"
        fi
    else
        echo "Downloading LhasaReact..."
        git clone --branch main https://github.com/moorhen-coot/LhasaReact.git &&\
        git -C LhasaReact fetch origin &&\
        git -C LhasaReact checkout $lhasa_commit || fail "Failed to clone and checkout LhasaReact"
    fi
    echo    
}

getglm() {
    cdcheckout
    if [ -r glm-$glm_release ]; then
        echo "Using existing glm"
    else
        echo "Downloading glm"
        curl -fL https://github.com/g-truc/glm/archive/refs/tags/$glm_release.tar.gz -o glm-$glm_release.tar.gz &&\
        echo &&\
        echo "Unpacking glm-$glm_release" &&\
        tar xf glm-$glm_release.tar.gz &&\
        cd ${MOORHEN_SOURCE_DIR} &&\
        echo "Linking glm headers" &&\
        mkdir -p include &&\
        cd include &&\
        rm -f glm &&\
        ln -s ../checkout/glm-$glm_release/glm glm || fail "Failed to download, unpack and link glm"
    fi
    echo
}

getrdkit() {
    cdcheckout
    if [ -r rdkit-$rdkit_release ]; then
        echo "Using existing rdkit"
    else
        echo "Downloading RDKit source"
        curl -fL https://github.com/rdkit/rdkit/archive/refs/tags/$rdkit_release.tar.gz -o "$rdkit_release.tar.gz" &&\
        echo &&\
        echo "Unpacking RDKit source" &&\
        tar xf "$rdkit_release.tar.gz" &&\
        echo &&\
        cd ${MOORHEN_SOURCE_DIR} &&\
        rm -f rdkit &&\
        ln -s checkout/rdkit-$rdkit_release rdkit &&\
        echo "Getting git version of rapidjson for RDKit" &&\
        cd ${MOORHEN_SOURCE_DIR}/checkout/rdkit-$rdkit_release/External &&\
        git clone https://github.com/Tencent/rapidjson.git rapidjson-1.1.0 || fail "Failed to download, unpack and set up RDKit"
    fi
    echo
}

getgraphene() {
    cdcheckout
    if [ -r graphene-$graphene_release ]; then
        echo "Using existing graphene"
    else
        echo "Downloading graphene source"
        curl -fL https://github.com/ebassi/graphene/archive/refs/tags/$graphene_release.tar.gz -o graphene_$graphene_release.tar.gz &&\
        echo &&\
        echo "Unpacking graphene source" &&\
        tar xf "graphene_$graphene_release.tar.gz" || fail "Failed to download and unpack graphene"
    fi
    echo
}

getsigcpp() {
    cdcheckout
    if [ -r libsigcplusplus-$libsigcpp_release ]; then
        echo "Using existing libsigcplusplus"
    else
        echo "Downloading libsigc++ source"
        curl -fL https://github.com/libsigcplusplus/libsigcplusplus/archive/refs/tags/$libsigcpp_release.tar.gz -o libsigcplusplus_$libsigcpp_release.tar.gz &&\
        echo &&\
        echo "Unpacking libsigc++ source" &&\
        tar xf "libsigcplusplus_$libsigcpp_release.tar.gz" || fail "Failed to download and unpack libsigc++"
    fi
    echo
}

getprivateer() {
    cdcheckout
    if [ -r privateer-wasm ]; then
        echo "Using existing privateer"
    else
        echo "Downloading and Unpacking Privateer"
        curl -fL https://github.com/glycojones/privateer/archive/refs/tags/moorhen-build-0.3.5.tar.gz -o privateer-wasm.tar.gz &&\
        tar xf privateer-wasm.tar.gz &&\
        mv privateer-moorhen-build-0.3.5 privateer-wasm &&\
        echo "Getting updated simdjson.h" &&\
        curl -fL https://raw.githubusercontent.com/simdjson/simdjson/master/singleheader/simdjson.h -o privateer-wasm/src/privateer/cpp/third-party/simdjson/simdjson.h &&\
        patch -p0 < ../patches/privateer-gemmi070.patch || fail "Failed to download, unpack and patch privateer"
    fi
    echo
}

getboost() {
    cdcheckout
    if [ -r boost-$boost_release ]; then
        echo "Using existing boost"
    else
        echo "Checking out boost"
        curl -fL https://github.com/boostorg/boost/releases/download/boost-$boost_release/boost-$boost_release-cmake.tar.gz -o boost_$boost_release.tar.gz &&\
        tar xf boost_$boost_release.tar.gz || fail "Failed to download and unpack boost"
    fi
    echo
}
