import os
from pydoc import doc
import subprocess

from attr import dataclass



script_dir = os.path.dirname(os.path.abspath(__file__))
store_dir = os.path.join(script_dir, "../src/store/")
export: str = "// Auto-generated file. Do not edit directly.\n//Use scripts/CreateStoreExport.py to regenerate.\n\n"
            

for file in os.listdir(store_dir):
    if file != "index.ts" and file != "MoorhenReduxStore.ts":
        with open(os.path.join(store_dir, file),"r") as f:
            for line in f:
                if "export const {" in line:
                    while "}" not in line:
                        export += line              
                        line = f.readline()
                    export += line.split('=')[0]
                    export += f" from \"./{file.split('.')[0]}\";\n"
                    
                    break
export = export.replace("const ", "")

output_file = os.path.join(store_dir, "index.ts")
if os.path.exists(output_file):
    os.remove(output_file)

with open(output_file,"w") as f:
    f.write(export)
    f.write("\n// Export store configuration and types\nexport { reducers, type MoorhenReduxStoreType, type RootState, type AppDispatch } from \"./MoorhenReduxStore\";")


# public exports
public_export: list[str] = []
with open(output_file,"r") as f:
    for line in f:
        if line.startswith("//"):
            continue

        if line.startswith("export { reducers"):
            break

        line = line.strip()
        line = line.replace("export {", "")
        line = line.split("}")[0]
        line = line.replace("\n","")
        line = line.replace(",","")
        lines = line.split(" ")
        public_export.extend(lines)

public_export = [item for item in public_export if item != '']

public_export_string = "export { " + ", ".join(public_export) + " } from \"@/store\";"

moorhen_file = os.path.join(script_dir, "../src/moorhen.ts")
marker = "// Export Redux store actions"

# Read the file and keep everything up to the marker
with open(moorhen_file, "r") as f:
    lines = f.readlines()

# Find the marker and truncate
with open(moorhen_file, "w") as f:
    for line in lines:
        if marker in line:
            break
        f.write(line)

# Append the new exports
with open(moorhen_file, "a") as f:
    f.write(marker + " are auto-generated by scripts/CreateStoreExport.py\n")
    f.write("\n" + "// do not edit below this line it will be overwritten by scripts/CreateStoreExport.py\n")
    f.write(public_export_string)
    


# ----------------------------------------- API extension for the store -----------------------------------------

@dataclass
class APIExport:
    name: str
    group: str
    payload: str
    docString: str
APIList: list[APIExport] = []

for file in os.listdir(store_dir):
    if file != "index.ts" and file != "MoorhenReduxStore.ts":
        with open(os.path.join(store_dir, file),"r") as f:
                      
            for line in f:
                if "//API" in line or "// API" in line:
                    if line.split("API")[1].strip() != "":
                        group_name = line.split("API")[1].strip()
                    else:
                        group_name = file.split('.')[0].replace("Slice","")

                    next_line = next(f)
                    if "/*" in next_line or "/**" in next_line:
                        if "*/" in next_line:
                            docstring = next_line.split("/*")[1].split("*/")[0].strip()
                        else:
                            docstring = next_line.split("/*")[1].strip()
                            while "*/" not in next_line:
                                next_line = next(f)
                                docstring += "\n" + next_line.strip()
                            docstring = docstring.split("*/")[0].strip()
                        fct_line = next(f)
                    elif "//" in next_line:
                        docstring = next_line.split("//")[1].strip()
                        fct_line = next(f)              
                    else:
                        docstring = ""
                        fct_line = next_line

                    payload = ""
                    name = fct_line.split(":")[0].strip()
                    
                    payload_start = fct_line.find("payload:")
                    if payload_start != -1:
                        payload_end = fct_line.find("; type", payload_start)
                        if payload_end != -1:
                            payload =fct_line[payload_start:payload_end].replace("payload:","").strip()

                    if payload == "":                
                        payload_start = fct_line.find("PayloadAction<")
                        if payload_start != -1:
                            payload_end = fct_line.find(">", payload_start)
                            if payload_end != -1:
                                payload = fct_line[payload_start+len("PayloadAction<"):payload_end].strip()
                    APIList.append(APIExport(name, group_name, payload, docstring))

ordered_APIList = sorted(APIList, key=lambda x: (x.group, x.name))
APIList = ordered_APIList

# Write the store extension functions for the APIs
storeImport = [api.name.strip() for api in APIList]
import_string = "import { RootState,"  + ",".join(storeImport) + " } from \"../store\";" + "// autogenerated import do not modify \n"

store_extension_file = os.path.join(script_dir, "../src/InstanceManager/StoreExtension.ts")

marker = "// -------------- Autogenerated store extension functions for APIs --------------"

with open(store_extension_file, "r") as f:
    lines = f.readlines()

with open(store_extension_file, "w") as f:
    f.write(import_string)

    for line in lines:
        if marker in line:
            break
        if "// autogenerated import" in line:
            continue
        f.write(line)

with open(store_extension_file, "a") as f:
    
    f.write(marker + "\n\n")
    API_group_name = ""
    
    for api in APIList:
        if api.group != API_group_name:            
            if API_group_name != "":
                f.write("    };\n}\n\n")

            API_group_name = api.group
            f.write(f"\tpublic get {API_group_name}()\n".replace("\t", "    ")) 
            f.write("{\n\t\tconst dispatch = this.dispatch;\n\t\treturn {\n".replace("\t", "    "))

        if api.docString != "":
            formatted_docstring  = api.docString.replace("\n", "\n\t\t\t")
            f.write(f"\t\t\t/** {formatted_docstring} */\n".replace("\t", "    "))

        formatted_payload = "value:"  + api.payload if api.payload != "" else ""
        f.write(f"\t\t\t{api.name}({formatted_payload})".replace("\t", "    ") + "{\n")
        value = "value" if api.payload != "" else ""
        f.write(f"\t\t\tdispatch({api.name}({value}));\n".replace("\t", "    ")) 
        f.write("\t\t\t},\n".replace("\t", "    "))
    f.write("}\n}\n}")

print(f"API have been populated in StoreExtension.ts with {len(APIList)} functions.")
# run eslint to check for mnissing types in the file
import subprocess

print("Running eslint to check for missing types in StoreExtension.ts...")
result = subprocess.run(
    ["npx", "eslint", "src/InstanceManager/StoreExtension.ts", "--ext", ".ts"],
    cwd="/home/clement/Moorhen/baby-gru",
    capture_output=True,
    text=True
)

if result.returncode != 0:
    print("Errors found:", result.stdout)
else:
    print("No errors found in StoreExtension.ts")