import os

script_dir = os.path.dirname(os.path.abspath(__file__))
store_dir = os.path.join(script_dir, "../src/store/")

export: str = "// Auto-generated file. Do not edit directly.\n//Use scripts/CreateStoreExport.py to regenerate.\n\n"

for file in os.listdir(store_dir):
    if file != "index.ts" and file != "MoorhenReduxStore.ts":
        with open(os.path.join(store_dir, file),"r") as f:
            for line in f:
                if "export const {" in line:
                    while "}" not in line:
                        export += line              
                        line = f.readline()
                    export += line.split('=')[0]
                    export += f" from \"./{file.split('.')[0]}\";\n"
                    
                    break
export = export.replace("const ", "")

output_file = os.path.join(store_dir, "index.ts")
if os.path.exists(output_file):
    os.remove(output_file)

with open(output_file,"w") as f:
    f.write(export)
    f.write("\n// Export store configuration and types\nexport { reducers, _MoorhenReduxStore, type MoorhenReduxStoreType, type RootState, type AppDispatch } from \"./MoorhenReduxStore\";")


# public exports
public_export: list[str] = []
with open(output_file,"r") as f:
    for line in f:
        if line.startswith("//"):
            continue

        if line.startswith("export { reducers"):
            break

        line = line.strip()
        line = line.replace("export {", "")
        line = line.split("}")[0]
        line = line.replace("\n","")
        line = line.replace(",","")
        lines = line.split(" ")
        public_export.extend(lines)

public_export = [item for item in public_export if item != '']

public_export_string = "export { " + ", ".join(public_export) + " } from \"@/store\";"

moorhen_file = os.path.join(script_dir, "../src/moorhen.ts")
marker = "// Export Redux store actions"

# Read the file and keep everything up to the marker
with open(moorhen_file, "r") as f:
    lines = f.readlines()

# Find the marker and truncate
with open(moorhen_file, "w") as f:
    for line in lines:
        if marker in line:
            break
        f.write(line)

# Append the new exports
with open(moorhen_file, "a") as f:
    f.write(marker + " are auto-generated by scripts/CreateStoreExport.py\n")
    f.write(public_export_string)
    f.write("\n" + "// do not edit below this line it will be overwritten by scripts/CreateStoreExport.py\n")