import { RootState,resetBackupSettings,setEnableTimeCapsule,setMakeBackups,setMaxBackupCount,setModificationCountBackupThreshold,setDisableFileUpload,setShowResidueSelection,setUseGemmi,setViewOnly,setDevMode,setShortCutsBlocked,setShowHoverInfo,setShownSidePanel,setSidePanelWidth,setEnableAtomHovering,setAtomLabelDepthMode,setGLLabelsFontFamily,setGLLabelsFontSize,hideMap,setContourLevel,setDefaultMapLitLines,setDefaultMapSamplingRate,setDefaultMapSurface,setMapAlpha,setMapColours,setMapLineWidth,setMapRadius,setMapStyle,setNegativeMapColours,setPositiveMapColours,setReContourMapOnlyOnMouseUp,showMap,setActiveMap,focusOnModal,hideModal,showModal,unFocusModal,disableUpdatingMaps,enableUpdatingMaps,resetMoleculeMapUpdates,setConnectedMoleculeMolNo,setCurrentScores,setShowScoresToast,triggerUpdate,resetDefaultMouseSettings,setContourWheelSensitivityFactor,setMouseSensitivity,setZoomWheelSensitivityFactor,resetRefinementSettings,setAnimateRefine,setEnableRefineAfterMod,setRefinementSelection,setUseRamaRefinementRestraints,setuseTorsionRefinementRestraints,resetSceneSettings,setAmbient,setBackgroundColor,setClipCap,setClipEnd,setClipStart,setDefaultBackgroundColor,setDefaultBondSmoothness,setDepthBlurDepth,setDepthBlurRadius,setDepthPeelLayers,setDiffuse,setDoAnaglyphStereo,setDoCrossEyedStereo,setDoEdgeDetect,setDoMultiView,setDoOutline,setDoPerspectiveProjection,setDoSSAO,setDoShadow,setDoShadowDepthDebug,setDoSideBySideStereo,setDoSpin,setDoThreeWayView,setDrawAxes,setDrawCrosshairs,setDrawEnvBOcc,setDrawFPS,setDrawMissingLoops,setDrawScaleBar,setEdgeDetectDepthScale,setEdgeDetectDepthThreshold,setEdgeDetectNormalScale,setEdgeDetectNormalThreshold,setFogClipOffset,setFogEnd,setFogStart,setGlViewportHeight,setGlViewportWidth,setHeight,setHoverSize,setIsDark,setLightPosition,setMultiViewColumns,setMultiViewRows,setOrigin,setPeelOpaqueSeparately,setPerspectiveEyeDistance,setResetClippingFogging,setSpecifyMultiViewRowsColumns,setSpecular,setSpecularPower,setSsaoBias,setSsaoRadius,setThreeWayViewOrder,setUseOffScreenBuffers,setWidth,setZoom,clearSnackbar,closeSnackbar,enqueueSnackbar,addVector,addVectors,emptyVectors,removeVector,removeVectorById,removeVectors,removeVectorsByIds,removeVectorsByTag,removeVectorsMatchingIDString } from "../store";// autogenerated import do not modify 
 
import { Dispatch, Store, UnknownAction } from "@reduxjs/toolkit";
import type { BottomPanelIDs, SidePanelIDs } from '@/components/panels';
import type { ModalCall } from '@/store/modalsSlice';
import type { MoorhenMap } from "@/utils"
import type { MoorhenVector } from "@/store/vectorsSlice";
import type { Tags } from "@/utils/tags";
import { ModalKey } from "@/components/interface-base/ModalBase/ModalsContainer";
import {  SnackbarPayload } from "@/store/snackbarSlice";



export class StoreExtension {
    private _dispatch: Dispatch<UnknownAction>;
    private _store: Store<RootState>;

    public get dispatch(): Dispatch<UnknownAction> {
        return this._dispatch;
    }
    public get store(): Store<RootState> {
        return this._store;
    }

    public subscribeToStore = <T>(selector: (state: RootState) => T, callback: (value: T) => void) => {
        let previousValue = selector(this._store.getState());

        return this._store.subscribe(() => {
            const newValue = selector(this._store.getState());
            if (previousValue !== newValue) {
                previousValue = newValue;
                callback(newValue);
            }
        });
    };

    public set dispatch(value: Dispatch<UnknownAction>) {
        this._dispatch = value;
    }
    public set store(value: Store<RootState>) {
        this._store = value;
    }

// -------------- Autogenerated store extension functions for APIs --------------

    public get backupSettings()
{
        const dispatch = this.dispatch;
        return {
            resetBackupSettings(){
            dispatch(resetBackupSettings());
            },
            setEnableTimeCapsule(value:boolean){
            dispatch(setEnableTimeCapsule(value));
            },
            setMakeBackups(value:boolean){
            dispatch(setMakeBackups(value));
            },
            setMaxBackupCount(value:number){
            dispatch(setMaxBackupCount(value));
            },
            setModificationCountBackupThreshold(value:number){
            dispatch(setModificationCountBackupThreshold(value));
            },
    };
}

    public get generalOptions()
{
        const dispatch = this.dispatch;
        return {
            /** disable file upload through the interface, API call still works normally */
            setDisableFileUpload(value:boolean){
            dispatch(setDisableFileUpload(value));
            },
            setShowResidueSelection(value:boolean){
            dispatch(setShowResidueSelection(value));
            },
            setUseGemmi(value:boolean){
            dispatch(setUseGemmi(value));
            },
            /** Set the view-only mode of the application. In view-only mode, users can interact with the visualisation but cannot make any modifications to the loaded structures or maps. */
            setViewOnly(value:boolean){
            dispatch(setViewOnly(value));
            },
    };
}

    public get globalUI()
{
        const dispatch = this.dispatch;
        return {
            /** Show dev menu and extra tools */
            setDevMode(value:boolean){
            dispatch(setDevMode(value));
            },
            /** Block or unblock shortcuts globally. This is used to prevent shortcut actions from being triggered when the user is typing in an input field, for example. */
            setShortCutsBlocked(value:boolean){
            dispatch(setShortCutsBlocked(value));
            },
            setShowHoverInfo(value:boolean){
            dispatch(setShowHoverInfo(value));
            },
            /** Display the side panel corresponding to the provided ID, or hide the side panel if the payload is null.
            @param value SidePanelIDs | null */
            setShownSidePanel(value:SidePanelIDs | null){
            dispatch(setShownSidePanel(value));
            },
            setSidePanelWidth(value:number){
            dispatch(setSidePanelWidth(value));
            },
    };
}

    public get hoveringStates()
{
        const dispatch = this.dispatch;
        return {
            setEnableAtomHovering(value:boolean){
            dispatch(setEnableAtomHovering(value));
            },
    };
}

    public get labelSettings()
{
        const dispatch = this.dispatch;
        return {
            setAtomLabelDepthMode(value:boolean){
            dispatch(setAtomLabelDepthMode(value));
            },
            setGLLabelsFontFamily(value:string){
            dispatch(setGLLabelsFontFamily(value));
            },
            setGLLabelsFontSize(value:number){
            dispatch(setGLLabelsFontSize(value));
            },
    };
}

    public get mapContourSettings()
{
        const dispatch = this.dispatch;
        return {
            hideMap(value:MoorhenMap){
            dispatch(hideMap(value));
            },
            setContourLevel(value:{ molNo: number; contourLevel: number }){
            dispatch(setContourLevel(value));
            },
            setDefaultMapLitLines(value:boolean){
            dispatch(setDefaultMapLitLines(value));
            },
            setDefaultMapSamplingRate(value:number){
            dispatch(setDefaultMapSamplingRate(value));
            },
            setDefaultMapSurface(value:boolean){
            dispatch(setDefaultMapSurface(value));
            },
            setMapAlpha(value:{ molNo: number; alpha: number }){
            dispatch(setMapAlpha(value));
            },
            setMapColours(value:{ molNo: number; rgb: { r: number; g: number; b: number } }){
            dispatch(setMapColours(value));
            },
            setMapLineWidth(value:number){
            dispatch(setMapLineWidth(value));
            },
            setMapRadius(value:{ molNo: number; radius: number }){
            dispatch(setMapRadius(value));
            },
            setMapStyle(value:{ molNo: number; style: "solid" | "lit-lines" | "lines" }){
            dispatch(setMapStyle(value));
            },
            setNegativeMapColours(value:{ molNo: number; rgb: { r: number; g: number; b: number } }){
            dispatch(setNegativeMapColours(value));
            },
            setPositiveMapColours(value:{ molNo: number; rgb: { r: number; g: number; b: number } }){
            dispatch(setPositiveMapColours(value));
            },
            /** If true the map will not be re-contoured when moving around, only on mouse up.
            helps performance on slower machines */
            setReContourMapOnlyOnMouseUp(value:boolean){
            dispatch(setReContourMapOnlyOnMouseUp(value));
            },
            showMap(value:MoorhenMap){
            dispatch(showMap(value));
            },
    };
}

    public get maps()
{
        const dispatch = this.dispatch;
        return {
            setActiveMap(value:MoorhenMap){
            dispatch(setActiveMap(value));
            },
    };
}

    public get modals()
{
        const dispatch = this.dispatch;
        return {
            focusOnModal(value:ModalKey){
            dispatch(focusOnModal(value));
            },
            hideModal(value:ModalKey){
            dispatch(hideModal(value));
            },
            showModal(value:ModalCall){
            dispatch(showModal(value));
            },
            unFocusModal(value:string){
            dispatch(unFocusModal(value));
            },
    };
}

    public get moleculeMapUpdate()
{
        const dispatch = this.dispatch;
        return {
            disableUpdatingMaps(){
            dispatch(disableUpdatingMaps());
            },
            enableUpdatingMaps(){
            dispatch(enableUpdatingMaps());
            },
            resetMoleculeMapUpdates(){
            dispatch(resetMoleculeMapUpdates());
            },
            setConnectedMoleculeMolNo(value:number){
            dispatch(setConnectedMoleculeMolNo(value));
            },
            setCurrentScores(value:{ rFactor: number; rFree: number; moorhenPoints: number }){
            dispatch(setCurrentScores(value));
            },
            setShowScoresToast(value:boolean){
            dispatch(setShowScoresToast(value));
            },
            triggerUpdate(value:number){
            dispatch(triggerUpdate(value));
            },
    };
}

    public get mouseSettings()
{
        const dispatch = this.dispatch;
        return {
            resetDefaultMouseSettings(){
            dispatch(resetDefaultMouseSettings());
            },
            setContourWheelSensitivityFactor(value:number){
            dispatch(setContourWheelSensitivityFactor(value));
            },
            setMouseSensitivity(value:number){
            dispatch(setMouseSensitivity(value));
            },
            setZoomWheelSensitivityFactor(value:number){
            dispatch(setZoomWheelSensitivityFactor(value));
            },
    };
}

    public get refinementSettings()
{
        const dispatch = this.dispatch;
        return {
            resetRefinementSettings(){
            dispatch(resetRefinementSettings());
            },
            setAnimateRefine(value:boolean){
            dispatch(setAnimateRefine(value));
            },
            setEnableRefineAfterMod(value:boolean){
            dispatch(setEnableRefineAfterMod(value));
            },
            setRefinementSelection(value:"SINGLE" | "TRIPLE" | "SPHERE"){
            dispatch(setRefinementSelection(value));
            },
            setUseRamaRefinementRestraints(value:boolean){
            dispatch(setUseRamaRefinementRestraints(value));
            },
            setuseTorsionRefinementRestraints(value:boolean){
            dispatch(setuseTorsionRefinementRestraints(value));
            },
    };
}

    public get sceneSettings()
{
        const dispatch = this.dispatch;
        return {
            resetSceneSettings(){
            dispatch(resetSceneSettings());
            },
            setAmbient(value:[number, number, number, number]){
            dispatch(setAmbient(value));
            },
            setBackgroundColor(value:[number, number, number, number]){
            dispatch(setBackgroundColor(value));
            },
            setClipCap(value:boolean){
            dispatch(setClipCap(value));
            },
            setClipEnd(value:number){
            dispatch(setClipEnd(value));
            },
            setClipStart(value:number){
            dispatch(setClipStart(value));
            },
            setDefaultBackgroundColor(value:[number, number, number, number]){
            dispatch(setDefaultBackgroundColor(value));
            },
            setDefaultBondSmoothness(value:number){
            dispatch(setDefaultBondSmoothness(value));
            },
            setDepthBlurDepth(value:number){
            dispatch(setDepthBlurDepth(value));
            },
            setDepthBlurRadius(value:number){
            dispatch(setDepthBlurRadius(value));
            },
            setDepthPeelLayers(value:number){
            dispatch(setDepthPeelLayers(value));
            },
            setDiffuse(value:[number, number, number, number]){
            dispatch(setDiffuse(value));
            },
            setDoAnaglyphStereo(value:boolean){
            dispatch(setDoAnaglyphStereo(value));
            },
            setDoCrossEyedStereo(value:boolean){
            dispatch(setDoCrossEyedStereo(value));
            },
            setDoEdgeDetect(value:boolean){
            dispatch(setDoEdgeDetect(value));
            },
            setDoMultiView(value:boolean){
            dispatch(setDoMultiView(value));
            },
            setDoOutline(value:boolean){
            dispatch(setDoOutline(value));
            },
            setDoPerspectiveProjection(value:boolean){
            dispatch(setDoPerspectiveProjection(value));
            },
            setDoSSAO(value:boolean){
            dispatch(setDoSSAO(value));
            },
            setDoShadow(value:boolean){
            dispatch(setDoShadow(value));
            },
            setDoShadowDepthDebug(value:boolean){
            dispatch(setDoShadowDepthDebug(value));
            },
            setDoSideBySideStereo(value:boolean){
            dispatch(setDoSideBySideStereo(value));
            },
            setDoSpin(value:boolean){
            dispatch(setDoSpin(value));
            },
            setDoThreeWayView(value:boolean){
            dispatch(setDoThreeWayView(value));
            },
            setDrawAxes(value:boolean){
            dispatch(setDrawAxes(value));
            },
            setDrawCrosshairs(value:boolean){
            dispatch(setDrawCrosshairs(value));
            },
            setDrawEnvBOcc(value:boolean){
            dispatch(setDrawEnvBOcc(value));
            },
            setDrawFPS(value:boolean){
            dispatch(setDrawFPS(value));
            },
            setDrawMissingLoops(value:boolean){
            dispatch(setDrawMissingLoops(value));
            },
            setDrawScaleBar(value:boolean){
            dispatch(setDrawScaleBar(value));
            },
            setEdgeDetectDepthScale(value:number){
            dispatch(setEdgeDetectDepthScale(value));
            },
            setEdgeDetectDepthThreshold(value:number){
            dispatch(setEdgeDetectDepthThreshold(value));
            },
            setEdgeDetectNormalScale(value:number){
            dispatch(setEdgeDetectNormalScale(value));
            },
            setEdgeDetectNormalThreshold(value:number){
            dispatch(setEdgeDetectNormalThreshold(value));
            },
            setFogClipOffset(value:number){
            dispatch(setFogClipOffset(value));
            },
            setFogEnd(value:number){
            dispatch(setFogEnd(value));
            },
            setFogStart(value:number){
            dispatch(setFogStart(value));
            },
            setGlViewportHeight(value:number){
            dispatch(setGlViewportHeight(value));
            },
            setGlViewportWidth(value:number){
            dispatch(setGlViewportWidth(value));
            },
            setHeight(value:number){
            dispatch(setHeight(value));
            },
            setHoverSize(value:number){
            dispatch(setHoverSize(value));
            },
            setIsDark(value:boolean){
            dispatch(setIsDark(value));
            },
            setLightPosition(value:[number, number, number, number]){
            dispatch(setLightPosition(value));
            },
            setMultiViewColumns(value:number){
            dispatch(setMultiViewColumns(value));
            },
            setMultiViewRows(value:number){
            dispatch(setMultiViewRows(value));
            },
            /** Set the origin of the scene to the provided coordinates.
            @param value [number, number, number] X, Y, Z coordinates */
            setOrigin(value:[number, number, number]){
            dispatch(setOrigin(value));
            },
            setPeelOpaqueSeparately(value:boolean){
            dispatch(setPeelOpaqueSeparately(value));
            },
            /** Move the eye towards or away from the view centre, in angstroms. This is what sets how
            strongly a perspective view converges: close in, the far side of a molecule shrinks
            markedly; far off, the view approaches orthographic. The framing stays put, because the
            projection's scale is derived from the same distance, so this is a dolly zoom rather
            than a zoom. Fog moves with the eye so that it stays where it was on the molecule.
            Clip needs no adjustment, being measured from the centre already. No effect under
            orthographic projection. */
            setPerspectiveEyeDistance(value:number){
            dispatch(setPerspectiveEyeDistance(value));
            },
            setResetClippingFogging(value:boolean){
            dispatch(setResetClippingFogging(value));
            },
            setSpecifyMultiViewRowsColumns(value:boolean){
            dispatch(setSpecifyMultiViewRowsColumns(value));
            },
            setSpecular(value:[number, number, number, number]){
            dispatch(setSpecular(value));
            },
            setSpecularPower(value:number){
            dispatch(setSpecularPower(value));
            },
            setSsaoBias(value:number){
            dispatch(setSsaoBias(value));
            },
            setSsaoRadius(value:number){
            dispatch(setSsaoRadius(value));
            },
            setThreeWayViewOrder(value:string){
            dispatch(setThreeWayViewOrder(value));
            },
            setUseOffScreenBuffers(value:boolean){
            dispatch(setUseOffScreenBuffers(value));
            },
            setWidth(value:number){
            dispatch(setWidth(value));
            },
            /** @param zoom level 1 = 22A
            or A/22 */
            setZoom(value:number){
            dispatch(setZoom(value));
            },
    };
}

    public get snackbar()
{
        const dispatch = this.dispatch;
        return {
            /** Clear all messages from the display. */
            clearSnackbar(){
            dispatch(clearSnackbar());
            },
            /** Remove the message with the specified unique identifier from the display. */
            closeSnackbar(value:{ uid: string }){
            dispatch(closeSnackbar(value));
            },
            /** Display a message on the interface with the provided content and styling options.
            @param message The content of the message to be displayed.
            @param variant The styling variant for the message, which can be "success", "error", "warning", or "info". Defaults to "info" if not provided.
            @param autoHideDuration The duration in milliseconds for which the message should be displayed before automatically hiding. If null, the message will not auto-hide. Defaults to 6000 milliseconds if not provided.
            @param uid An optional unique identifier for the message. If not provided, a unique ID will be generated using the current timestamp and a random number. */
            enqueueSnackbar(value:SnackbarPayload){
            dispatch(enqueueSnackbar(value));
            },
    };
}

    public get vectors()
{
        const dispatch = this.dispatch;
        return {
            addVector(value:MoorhenVector){
            dispatch(addVector(value));
            },
            addVectors(value:MoorhenVector[]){
            dispatch(addVectors(value));
            },
            emptyVectors(){
            dispatch(emptyVectors());
            },
            removeVector(value:MoorhenVector){
            dispatch(removeVector(value));
            },
            /** * Remove one vector by its uniqueId, without needing the vector itself. */
            removeVectorById(value:string){
            dispatch(removeVectorById(value));
            },
            removeVectors(value:MoorhenVector[]){
            dispatch(removeVectors(value));
            },
            /** * Remove several vectors by their uniqueIds, without needing the vectors themselves. */
            removeVectorsByIds(value:string[]){
            dispatch(removeVectorsByIds(value));
            },
            /** *
            * Remove every vector carrying all of the given tags. One pair removes a whole group,
            * several narrow it: { source: "xpid" } takes every XPID vector, and adding
            * { molecule: uid } restricts it to one molecule's. An empty query removes nothing, so
            * that a tag object which came out empty by accident cannot clear the scene; use
            * emptyVectors to mean all of them. */
            removeVectorsByTag(value:Tags){
            dispatch(removeVectorsByTag(value));
            },
            /** *
            * @deprecated Matches a substring of uniqueId, from when a tag was written into the
            * identifier. Use removeVectorsByTag. Kept because it is public and takes an arbitrary
            * string, so identifiers in the wild carry tags that cannot be migrated. */
            removeVectorsMatchingIDString(value:string){
            dispatch(removeVectorsMatchingIDString(value));
            },
}
}
}