export const modalKeys = Object.freeze({
    MODELS: "models",
    MAPS: "maps",
    ACEDRG: "acedrg",
    SEQ_QUERY: "query-seq",
    SCRIPTING: "scripting",
    SHOW_CONTROLS: "show-controls",
    FIT_LIGAND: "fit-ligand",
    RAMA_PLOT: "rama-plot",
    DIFF_MAP_PEAKS: "diff-map-peaks",
    VALIDATION_PLOT: "validation-plot",
    MMRRCC: "mmrrcc",
    WATER_VALIDATION: "water-validation",
    LIGAND_VALIDATION: "lig-validation",
    FILL_PART_RES: "fill-partial-residues",
    PEPTIDE_FLIPS: "pepflips",
    UNMODELLED_BLOBS: "unmodelled-blobs",
    CARB_VALIDATION: "carb-validation",
    SLICE_N_DICE: "slice-n-dice",
    SUPERPOSE_MODELS: "superpose",
    SCENE_SETTINGS: "scene-settings",
    LHASA: "lhasa",
    QSCORE: "qscore",
    JSON_VALIDATION: "json-validation",
    MRBUMP: "mrbump",
    MRPARSE: "mrparse",
    COLOR_MAP_BY_MAP: "colour-map-by-map",
    VECTORS: "vectors",
    OVERLAYS2D: "overlays-2d",
    PAEPLOT: "pae-plot",
});

export const representationLabelMapping = Object.freeze({
    rama: "Ramachandran Balls",
    rotamer: "Rotamer Dodec.",
    CBs: "Bonds",
    CAs: "C-Alpha",
    CRs: "Ribbons",
    CDs: "Contact dots",
    MolecularSurface: "Mol Surface",
    gaussian: "Gaussian Surface",
    ligands: "Ligands",
    DishyBases: "Bases",
    VdwSpheres: "Spheres",
    allHBonds: "H-Bonds",
    glycoBlocks: "Glyco-Blocks",
    restraints: "Restraints",
    MetaBalls: "MetaBalls",
    adaptativeBonds: "Adaptive Bonds",
    residue_environment: "Res. Environment",
    environment: "Environment",
});

export const COOT_BOND_REPRESENTATIONS = ["MetaBalls", "CBs", "VdwSpheres", "CAs", "ligands"];
export const M2T_REPRESENTATIONS = ["CRs", "DishyBases", "StickBases", "VdWSurface", "Calpha", "MolecularSurface"];

export const residueCodesOneToThree = Object.freeze({
    C: "CYS",
    D: "ASP",
    S: "SER",
    Q: "GLN",
    K: "LYS",
    I: "ILE",
    P: "PRO",
    T: "THR",
    F: "PHE",
    N: "ASN",
    G: "GLY",
    H: "HIS",
    L: "LEU",
    R: "ARG",
    W: "TRP",
    A: "ALA",
    V: "VAL",
    E: "GLU",
    Y: "TYR",
    M: "MET",
    UNK: "UNKOWN",
    X: "UNKOWN",
    "-": "MISSING",
});

export const residueCodesThreeToOne = Object.freeze({
    ALA: "A",
    ARG: "R",
    ASN: "N",
    ASP: "D",
    CYS: "C",
    GLN: "Q",
    GLU: "E",
    GLY: "G",
    HIS: "H",
    ILE: "I",
    LEU: "L",
    LYS: "K",
    MET: "M",
    PHE: "F",
    PRO: "P",
    SER: "S",
    THR: "T",
    TRP: "W",
    TYR: "Y",
    VAL: "V",
    UNK: "X",
});

export const nucleotideCodesOneToThree = Object.freeze({
    A: "A",
    T: "T",
    G: "G",
    C: "C",
    U: "U",
    N: "N",
    I: "I",
    X: "UNKOWN",
    UNK: "UNKOWN",
    "-": "MISSING",
});

export const nucleotideCodesThreeToOne = Object.freeze({
    A: "A",
    T: "T",
    G: "G",
    C: "C",
    U: "U",
    N: "N",
    I: "I",
    DT: "T",
    DG: "G",
    DC: "C",
    DA: "A",
    DU: "U",
    ADE: "A",
    THY: "T",
    GUA: "G",
    CYT: "C",
    URA: "U",
    PSU: "U",
    UNKOWN: "X",
    UNK: "X",
    MISSING: "-",
});

export const windowsFonts = [
    "Arial",
    "Arial Black",
    "Bahnschrift",
    "Calibri",
    "Cambria",
    "Cambria Math",
    "Candara",
    "Comic Sans MS",
    "Consolas",
    "Constantia",
    "Corbel",
    "Courier New",
    "Ebrima",
    "Franklin Gothic Medium",
    "Gabriola",
    "Gadugi",
    "Georgia",
    "HoloLens MDL2 Assets",
    "Impact",
    "Ink Free",
    "Javanese Text",
    "Leelawadee UI",
    "Lucida Console",
    "Lucida Sans Unicode",
    "Malgun Gothic",
    "Marlett",
    "Microsoft Himalaya",
    "Microsoft JhengHei",
    "Microsoft New Tai Lue",
    "Microsoft PhagsPa",
    "Microsoft Sans Serif",
    "Microsoft Tai Le",
    "Microsoft YaHei",
    "Microsoft Yi Baiti",
    "MingLiU-ExtB",
    "Mongolian Baiti",
    "MS Gothic",
    "MV Boli",
    "Myanmar Text",
    "Nirmala UI",
    "Palatino Linotype",
    "Segoe MDL2 Assets",
    "Segoe Print",
    "Segoe Script",
    "Segoe UI",
    "Segoe UI Historic",
    "Segoe UI Emoji",
    "Segoe UI Symbol",
    "SimSun",
    "Sitka",
    "Sylfaen",
    "Symbol",
    "Tahoma",
    "Times New Roman",
    "Trebuchet MS",
    "Verdana",
    "Webdings",
    "Wingdings",
    "Yu Gothic",
];

export const macFonts = [
    "American Typewriter",
    "Andale Mono",
    "Arial",
    "Arial Black",
    "Arial Narrow",
    "Arial Rounded MT Bold",
    "Arial Unicode MS",
    "Avenir",
    "Avenir Next",
    "Avenir Next Condensed",
    "Baskerville",
    "Big Caslon",
    "Bodoni 72",
    "Bodoni 72 Oldstyle",
    "Bodoni 72 Smallcaps",
    "Bradley Hand",
    "Brush Script MT",
    "Chalkboard",
    "Chalkboard SE",
    "Chalkduster",
    "Charter",
    "Cochin",
    "Comic Sans MS",
    "Copperplate",
    "Courier",
    "Courier New",
    "Didot",
    "DIN Alternate",
    "DIN Condensed",
    "Futura",
    "Geneva",
    "Georgia",
    "Gill Sans",
    "Helvetica",
    "Helvetica Neue",
    "Herculanum",
    "Hoefler Text",
    "Impact",
    "Lucida Grande",
    "Luminari",
    "Marker Felt",
    "Menlo",
    "Microsoft Sans Serif",
    "Monaco",
    "Noteworthy",
    "Optima",
    "Palatino",
    "Papyrus",
    "Phosphate",
    "Rockwell",
    "Savoye LET",
    "SignPainter",
    "Skia",
    "Snell Roundhand",
    "Tahoma",
    "Times",
    "Times New Roman",
    "Trattatello",
    "Trebuchet MS",
    "Verdana",
    "Zapfino",
];

export const linuxFonts = [
    "Liberation Sans",
    "Nimbus Sans L",
    "FreeSans",
    "DejaVu Sans",
    "Bitstream Vera Sans",
    "Geneva",
    "Liberation Serif",
    "Nimbus Roman No 9 L",
    "FreeSerif",
    "Hoefler Text",
    "Times",
    "Times New Roman",
    "Bitstream Charter",
    "URW Palladio L",
    "Palatino",
    "Palatino Linotype",
    "Book Antiqua",
    "DejaVu Serif",
    "Bitstream Vera Serif",
    "Century Schoolbook L",
    "Lucida Bright",
    "Georgia",
    "Liberation Mono",
    "Nimbus Mono L",
    "FreeMono",
    "Bitstream Vera Mono",
    "Lucida Console",
    "DejaVu Mono",
];

export const webSafeFonts = [
    "Comic Sans",
    "Courier New",
    "Georgia",
    "Times New Roman",
    "Verdana",
    "Trebuchet MS",
    "Palatino",
    "Tahoma",
    "Arial",
    "Impact",
];

export const allFontsSet = new Set([webSafeFonts, windowsFonts, macFonts, linuxFonts].flat().sort());

export const railSpecies = [
    "African Swamphen",
    "Allens Gallinule",
    "American Coot",
    "Andean Coot",
    "Australasian Swamphen",
    "Azure Gallinule",
    "Baillons Crake",
    "Band-bellied Crake",
    "Black Crake",
    "Black Rail",
    "Black-backed Moorhen",
    "Black-backed Swamphen",
    "Black-tailed Nativehen",
    "Black-tailed Waterhen",
    "Blackish Crake",
    "Blackish Rail",
    "Brown Crake",
    "Brown Swamphen",
    "Caribbean Coot",
    "Chatham Swamphen",
    "Chestnut Gallinule",
    "Chestnut-headed Crake",
    "Chiriqui Crake",
    "Common Gallinule",
    "Common Moorhen",
    "Common Waterhen",
    "Congo Moorhen",
    "Cuban Gallinule",
    "Egret",
    "Dusky Moorhen",
    "Eared Rail",
    "Eurasian Coot",
    "Eurasian Moorhen",
    "Fiji Rail",
    "Forest Crake",
    "Giant Coot",
    "Gough Moorhen",
    "Guam Rail",
    "Gray-headed Swamphen",
    "Great-crested Grebe",
    "Green-backed Gallinule",
    "Grey-headed Swamphen",
    "Hawaiian Gallinule",
    "Hawaiian Moorhen",
    "Henderson Crake",
    "Horned Coot",
    "King Rail",
    "Kosrae Crake",
    "Laysan Rail",
    "Least Moorhen",
    "Lesser Moorhen",
    "Little Crake",
    "Lord Howe Swamphen",
    "Makira Moorhen",
    "Makira Woodhen",
    "Maori Hen",
    "Mauritian Moorhen",
    "Micronesian Moorhen",
    "Moluccan Swamphen",
    "New Britain Swamphen",
    "North Island Takahe",
    "Pacific Swamphen",
    "Paint-billed Crake",
    "Palau Swamphen",
    "Papuan Swamphen",
    "Purple Gallinule",
    "Purple Swamphen",
    "Red Rail",
    "Red-fronted Coot",
    "Red-gartered Coot",
    "Red-knobbed Coot",
    "Red-legged Crake",
    "Reunion Ibis",
    "Roviana Rail",
    "Samoa Swamphen",
    "Samoan Moorhen",
    "Samoan Woodhen",
    "Slaty-breasted Rail",
    "Slaty-legged crake",
    "Sora",
    "Speckled Gallinule",
    "Spot-flanked gallinule",
    "Spotless Crake",
    "Tahiti Swamphen",
    "Takahe",
    "Talaud Rail",
    "Tasmanian Nativehen",
    "Tongan Moorhen",
    "Tristan Moorhen",
    "Triton Moorhen",
    "Vanuatu Swamphen",
    "Watercock",
    "Weka",
    "Western Swamphen",
    "White Gallinule",
    "White-breasted Waterhen",
    "White-browed Crake",
    "White-winged Coot",
    "Yellow Rail",
    "Yellow-breasted Crake",
];
