#include "moorhen-wrappers-helpers.h"

EMSCRIPTEN_BINDINGS(moorhen_container) {
    class_<molecules_container_t>("molecules_container_t")
    .constructor<bool>()
    .function("dedust_map",&molecules_container_t::dedust_map)
    .function("get_overlap_dots",&molecules_container_t::get_overlap_dots)
    .function("set_max_number_of_simple_mesh_vertices",&molecules_container_t::set_max_number_of_simple_mesh_vertices)
    .function("get_max_number_of_simple_mesh_vertices",&molecules_container_t::get_max_number_of_simple_mesh_vertices)
    .function("set_colour_map_for_map_coloured_by_other_map",&molecules_container_t::set_colour_map_for_map_coloured_by_other_map)
    .function("get_mutation_info",&molecules_container_t::get_mutation_info)
    .function("get_ligand_validation_vs_dictionary",&molecules_container_t::get_ligand_validation_vs_dictionary)
    .function("get_validation_vs_dictionary_for_selection",&molecules_container_t::get_validation_vs_dictionary_for_selection)
    .function("rotate_around_bond",&molecules_container_t::rotate_around_bond)
    .function("read_extra_restraints",&molecules_container_t::read_extra_restraints)
    .function("get_sum_density_for_atoms_in_residue",&molecules_container_t::get_sum_density_for_atoms_in_residue)
    .function("get_residue_sidechain_average_position",&molecules_container_t::get_residue_sidechain_average_position)
    .function("get_residue_CA_position",&molecules_container_t::get_residue_CA_position)
    .function("get_residue_average_position",&molecules_container_t::get_residue_average_position)
    .function("get_missing_residue_ranges",&molecules_container_t::get_missing_residue_ranges)
    .function("get_ligand_distortion",&molecules_container_t::get_ligand_distortion)
    .function("add_lsq_superpose_atom_match",&molecules_container_t::add_lsq_superpose_atom_match)
    .function("split_residue_using_map",&molecules_container_t::split_residue_using_map)
    .function("flood",&molecules_container_t::flood)
    .function("copy_molecule",&molecules_container_t::copy_molecule)
    .function("add_terminal_residue_directly",&molecules_container_t::add_terminal_residue_directly)
    .function("mmcif_tests", &molecules_container_t::mmcif_tests)
    .function("M2T_updateIntParameter", &molecules_container_t::M2T_updateIntParameter)
    .function("M2T_updateFloatParameter", &molecules_container_t::M2T_updateFloatParameter)
    .function("clear_lsq_matches", &molecules_container_t::clear_lsq_matches)
    .function("add_lsq_superpose_match", &molecules_container_t::add_lsq_superpose_match)
    .function("assign_sequence",&molecules_container_t::assign_sequence)
    .function("associate_sequence",&molecules_container_t::associate_sequence)
    .function("average_map",&molecules_container_t::average_map)
    .function("get_group_for_monomer",&molecules_container_t::get_group_for_monomer)
    .function("get_groups_for_monomers",&molecules_container_t::get_groups_for_monomers)
    .function("get_hb_type",&molecules_container_t::get_hb_type)
    .function("get_imol_enc_any",&molecules_container_t::get_imol_enc_any)
    //this requires std::pair<short int, clipper::RTop_orth>
    //.function("get_lsq_matrix",&molecules_container_t::get_lsq_matrix)
    .function("get_median_temperature_factor",&molecules_container_t::get_median_temperature_factor)
    .function("get_number_of_map_sections",&molecules_container_t::get_number_of_map_sections)
    .function("get_number_of_molecules",&molecules_container_t::get_number_of_molecules)
    .function("get_octahemisphere",&molecules_container_t::get_octahemisphere)
    .function("get_residues_near_residue",&molecules_container_t::get_residues_near_residue)
    .function("get_use_rama_plot_restraints",&molecules_container_t::get_use_rama_plot_restraints)
    .function("get_use_torsion_restraints",&molecules_container_t::get_use_torsion_restraints)
    .function("make_power_scaled_map",&molecules_container_t::make_power_scaled_map)
    .function("print_secondary_structure_info",&molecules_container_t::print_secondary_structure_info)
    .function("read_coordinates",&molecules_container_t::read_coordinates)
    .function("refine_residues",&molecules_container_t::refine_residues)
    .function("regen_map",&molecules_container_t::regen_map)
    .function("set_add_waters_sigma_cutoff",&molecules_container_t::set_add_waters_sigma_cutoff)
    .function("set_add_waters_variance_limit",&molecules_container_t::set_add_waters_variance_limit)
    .function("set_molecule_name",&molecules_container_t::set_molecule_name)
    .function("write_coordinates",&molecules_container_t::write_coordinates)
    .function("get_density_at_position",&molecules_container_t::get_density_at_position)
    .function("get_dictionary_conformers",&molecules_container_t::get_dictionary_conformers)
    .function("lsq_superpose", &molecules_container_t::lsq_superpose)
    .function("new_molecule", &molecules_container_t::new_molecule)
    .function("get_header_info", &molecules_container_t::get_header_info)
    .function("copy_dictionary", &molecules_container_t::copy_dictionary)
    .function("end_delete_closed_molecules", &molecules_container_t::end_delete_closed_molecules)
    .function("make_ensemble", &molecules_container_t::make_ensemble)
    .function("match_ligand_torsions_and_position_using_cid", &molecules_container_t::match_ligand_torsions_and_position_using_cid)
    .function("set_rama_plot_restraints_weight", &molecules_container_t::set_rama_plot_restraints_weight)
    .function("get_rama_plot_restraints_weight", &molecules_container_t::get_rama_plot_restraints_weight)
    .function("set_use_rama_plot_restraints", &molecules_container_t::set_use_rama_plot_restraints)
    .function("set_use_torsion_restraints", &molecules_container_t::set_use_torsion_restraints)
    .function("set_torsion_restraints_weight", &molecules_container_t::set_torsion_restraints_weight)
    .function("get_torsion_restraints_weight", &molecules_container_t::get_torsion_restraints_weight)
    .function("minimize_energy", &molecules_container_t::minimize_energy)
    .function("set_refinement_is_verbose", &molecules_container_t::set_refinement_is_verbose)
    .function("split_multi_model_molecule", &molecules_container_t::split_multi_model_molecule)
    .function("print_non_drawn_bonds", &molecules_container_t::print_non_drawn_bonds)
    .function("pop_back", &molecules_container_t::pop_back)
    .function("get_use_gemmi", &molecules_container_t::get_use_gemmi)
    .function("set_use_gemmi", &molecules_container_t::set_use_gemmi)
    .function("generate_local_self_restraints", &molecules_container_t::generate_local_self_restraints)
    .function("get_ncs_related_chains", &molecules_container_t::get_ncs_related_chains)
    .function("set_max_number_of_threads", &molecules_container_t::set_max_number_of_threads)
    .function("set_map_is_contoured_with_thread_pool", &molecules_container_t::set_map_is_contoured_with_thread_pool)
    .function("is_EM_map",&molecules_container_t::is_EM_map)
    .function("scale_map",&molecules_container_t::scale_map)
    .function("set_map_sampling_rate",&molecules_container_t::set_map_sampling_rate)
    .function("get_mesh_for_ligand_validation_vs_dictionary",&molecules_container_t::get_mesh_for_ligand_validation_vs_dictionary)
    .function("molecule_to_mmCIF_string", &molecules_container_t::molecule_to_mmCIF_string)
    .function("molecule_to_PDB_string", &molecules_container_t::molecule_to_PDB_string)
    .function("clear_refinement",&molecules_container_t::clear_refinement)
    .function("fourier_shell_correlation",&molecules_container_t::fourier_shell_correlation)
    .function("get_suggested_initial_contour_level",&molecules_container_t::get_suggested_initial_contour_level)
    .function("clear_target_position_restraints",&molecules_container_t::clear_target_position_restraints)
    .function("add_target_position_restraint_and_refine",&molecules_container_t::add_target_position_restraint_and_refine)
    .function("refine",&molecules_container_t::refine)
    .function("init_refinement_of_molecule_as_fragment_based_on_reference",&molecules_container_t::init_refinement_of_molecule_as_fragment_based_on_reference)
    .function("copy_fragment_for_refinement_using_cid",&molecules_container_t::copy_fragment_for_refinement_using_cid)
    .function("add_target_position_restraint",&molecules_container_t::add_target_position_restraint)
    .function("get_h_bonds",&molecules_container_t::get_h_bonds)
    .function("change_to_next_rotamer",&molecules_container_t::change_to_next_rotamer)
    .function("change_to_previous_rotamer",&molecules_container_t::change_to_previous_rotamer)
    .function("change_to_first_rotamer",&molecules_container_t::change_to_first_rotamer)
    .function("set_user_defined_atom_colour_by_selection",&molecules_container_t::set_user_defined_atom_colour_by_selection)
    .function("set_user_defined_bond_colours",&molecules_container_t::set_user_defined_bond_colours)
    .function("set_colour_wheel_rotation_base",&molecules_container_t::set_colour_wheel_rotation_base)
    .function("set_base_colour_for_bonds",&molecules_container_t::set_base_colour_for_bonds)
    .function("set_use_bespoke_carbon_atom_colour",&molecules_container_t::set_use_bespoke_carbon_atom_colour)
    .function("get_symmetry",&molecules_container_t::get_symmetry)
    .function("fit_to_map_by_random_jiggle_using_cid",&molecules_container_t::fit_to_map_by_random_jiggle_using_cid)
    .function("get_active_atom",&molecules_container_t::get_active_atom)
    .function("is_a_difference_map",&molecules_container_t::is_a_difference_map)
    .function("add_hydrogen_atoms",&molecules_container_t::add_hydrogen_atoms)
    .function("delete_hydrogen_atoms",&molecules_container_t::delete_hydrogen_atoms)
    .function("get_gaussian_surface",&molecules_container_t::get_gaussian_surface)
    .function("get_monomer_from_dictionary",&molecules_container_t::get_monomer_from_dictionary)
    .function("get_molecular_representation_mesh",&molecules_container_t::get_molecular_representation_mesh)
    .function("get_map_weight",&molecules_container_t::get_map_weight)
    .function("set_map_weight",&molecules_container_t::set_map_weight)
    .function("set_show_timings",&molecules_container_t::set_show_timings)
    .function("get_molecule_name",&molecules_container_t::get_molecule_name)
    .function("non_standard_residue_types_in_model",&molecules_container_t::non_standard_residue_types_in_model)
    .function("partition_map_by_chain",&molecules_container_t::partition_map_by_chain)
    .function("get_map_mean",&molecules_container_t::get_map_mean)
    .function("get_map_rmsd_approx",&molecules_container_t::get_map_rmsd_approx)
    .function("set_draw_missing_residue_loops",&molecules_container_t::set_draw_missing_residue_loops)
    .function("set_make_backups",&molecules_container_t::set_make_backups)
    .function("get_chains_in_model",&molecules_container_t::get_chains_in_model)
    .function("get_residue_names_with_no_dictionary",&molecules_container_t::get_residue_names_with_no_dictionary)
    .function("get_residue_name", &molecules_container_t::get_residue_name)
    .function("get_molecule_diameter", &molecules_container_t::get_molecule_diameter)
    .function("multiply_residue_temperature_factors", &molecules_container_t::multiply_residue_temperature_factors)
    .function("shift_field_b_factor_refinement", &molecules_container_t::shift_field_b_factor_refinement)
    .function("change_chain_id", &molecules_container_t::change_chain_id)
    .function("write_map",&molecules_container_t::write_map)
    .function("delete_atom",&molecules_container_t::delete_atom)
    .function("delete_atom_using_cid",&molecules_container_t::delete_atom_using_cid)
    .function("delete_residue",&molecules_container_t::delete_residue)
    .function("delete_residue_using_cid",&molecules_container_t::delete_residue_using_cid)
    .function("delete_residue_atoms_with_alt_conf",&molecules_container_t::delete_residue_atoms_with_alt_conf)
    .function("delete_residue_atoms_using_cid",&molecules_container_t::delete_residue_atoms_using_cid)
    .function("delete_side_chain",&molecules_container_t::delete_side_chain)
    .function("delete_chain_using_cid",&molecules_container_t::delete_chain_using_cid)
    .function("get_molecule_centre",&molecules_container_t::get_molecule_centre)
    .function("peptide_omega_analysis",&molecules_container_t::peptide_omega_analysis)
    .function("calculate_new_rail_points",&molecules_container_t::calculate_new_rail_points)
    .function("rail_points_total",&molecules_container_t::rail_points_total)
    .function("sfcalc_genmap",&molecules_container_t::sfcalc_genmap)
    .function("sfcalc_genmaps_using_bulk_solvent",&molecules_container_t::sfcalc_genmaps_using_bulk_solvent)
    .function("add_colour_rule",&molecules_container_t::add_colour_rule)
    .function("delete_colour_rules",&molecules_container_t::delete_colour_rules)
    .function("add_colour_rules_multi",&molecules_container_t::add_colour_rules_multi)
    .function("fit_ligand_right_here",&molecules_container_t::fit_ligand_right_here)
    .function("fit_ligand",&molecules_container_t::fit_ligand)
    .function("fit_to_map_by_random_jiggle",&molecules_container_t::fit_to_map_by_random_jiggle)
    .function("get_svg_for_residue_type",&molecules_container_t::get_svg_for_residue_type)
    .function("get_svg_for_2d_ligand_environment_view",&molecules_container_t::get_svg_for_2d_ligand_environment_view)
    .function("is_valid_model_molecule",&molecules_container_t::is_valid_model_molecule)
    .function("is_valid_map_molecule",&molecules_container_t::is_valid_map_molecule)
    .function("read_pdb",&molecules_container_t::read_pdb)
    .function("read_ccp4_map",&molecules_container_t::read_ccp4_map)
    .function("read_mtz",&molecules_container_t::read_mtz)
    .function("residue_cid_to_residue_spec",&molecules_container_t::residue_cid_to_residue_spec)
    //   int import_cif_dictionary(const std::string &cif_file_name, int imol_enc);
    .function("import_cif_dictionary",&molecules_container_t::import_cif_dictionary)
    .function("density_fit_analysis",&molecules_container_t::density_fit_analysis)
    .function("get_number_of_atoms",&molecules_container_t::get_number_of_atoms)
    .function("get_number_of_hydrogen_atoms",&molecules_container_t::get_number_of_hydrogen_atoms)
    //Using allow_raw_pointers(). Perhaps suggests we need to do something different from exposing mmdb pointers to JS.
    .function("get_residue",&molecules_container_t::get_residue, allow_raw_pointers())
    .function("get_atom",&molecules_container_t::get_atom, allow_raw_pointers())
    .function("flipPeptide_cid",   select_overload<int(int, const std::string&,      const std::string&)>(&molecules_container_t::flip_peptide_using_cid))
    .function("flipPeptide",       select_overload<int(int, const coot::atom_spec_t&,const std::string&)>(&molecules_container_t::flip_peptide))
    .function("side_chain_180",    select_overload<int(int, const std::string&)>                         (&molecules_container_t::side_chain_180))
    .function("eigen_flip_ligand", select_overload<void(int, const std::string&)>                        (&molecules_container_t::eigen_flip_ligand_using_cid))
    .function("jed_flip",          select_overload<std::string(int, const std::string&, bool)>           (&molecules_container_t::jed_flip))
    .function("add_terminal_residue_directly_using_cid",&molecules_container_t::add_terminal_residue_directly_using_cid)
    .function("test_origin_cube",&molecules_container_t::test_origin_cube)
    .function("get_ramachandran_validation_markup_mesh",&molecules_container_t::get_ramachandran_validation_markup_mesh)
    .function("get_rotamer_dodecs",&molecules_container_t::get_rotamer_dodecs)
    .function("get_rotamer_dodecs_instanced",&molecules_container_t::get_rotamer_dodecs_instanced)
    .function("auto_fit_rotamer",&molecules_container_t::auto_fit_rotamer)
    .function("rigid_body_fit",&molecules_container_t::rigid_body_fit)
    .function("cis_trans_convert",&molecules_container_t::cis_trans_convert)
    .function("get_lsq_matrix",&molecules_container_t::get_lsq_matrix)
    .function("get_map_contours_mesh",&molecules_container_t::get_map_contours_mesh)
    .function("geometry_init_standard",&molecules_container_t::geometry_init_standard)
    .function("fill_rotamer_probability_tables",&molecules_container_t::fill_rotamer_probability_tables)
    .function("copy_fragment_using_residue_range",&molecules_container_t::copy_fragment_using_residue_range)
    .function("copy_fragment_using_cid",&molecules_container_t::copy_fragment_using_cid)
    .function("close_molecule",&molecules_container_t::close_molecule)
    .function("undo",&molecules_container_t::undo)
    .function("redo",&molecules_container_t::redo)
    .function("refine_residues_using_atom_cid",&molecules_container_t::refine_residues_using_atom_cid)
    .function("refine_residue_range",&molecules_container_t::refine_residue_range)
    .function("contact_dots_for_ligand",&molecules_container_t::contact_dots_for_ligand)
    .function("all_molecule_contact_dots",&molecules_container_t::all_molecule_contact_dots)
    .function("get_chemical_features_mesh",&molecules_container_t::get_chemical_features_mesh)
    .function("set_imol_refinement_map",&molecules_container_t::set_imol_refinement_map)
    .function("mutate",&molecules_container_t::mutate)
    .function("fill_partial_residue",&molecules_container_t::fill_partial_residue)
    .function("fill_partial_residues",&molecules_container_t::fill_partial_residues)
    .function("add_alternative_conformation",&molecules_container_t::add_alternative_conformation)
    .function("delete_using_cid",&molecules_container_t::delete_using_cid)
    .function("get_bonds_mesh",&molecules_container_t::get_bonds_mesh)
    .function("get_goodsell_style_mesh_instanced", &molecules_container_t::get_goodsell_style_mesh_instanced)
    .function("clear", &molecules_container_t::clear)
    .function("get_bonds_mesh_instanced",&molecules_container_t::get_bonds_mesh_instanced)
    .function("get_bonds_mesh_for_selection_instanced",&molecules_container_t::get_bonds_mesh_for_selection_instanced)
    .function("go_to_blob",&molecules_container_t::go_to_blob)
    .function("get_monomer",&molecules_container_t::get_monomer)
    .function("get_monomer_and_position_at",&molecules_container_t::get_monomer_and_position_at)
    .function("move_molecule_to_new_centre",&molecules_container_t::move_molecule_to_new_centre)
    .function("apply_transformation_to_atom_selection",&molecules_container_t::apply_transformation_to_atom_selection)
    .function("new_positions_for_residue_atoms",&molecules_container_t::new_positions_for_residue_atoms)
    .function("new_positions_for_atoms_in_residues",&molecules_container_t::new_positions_for_atoms_in_residues)
    //.function("get_interesting_places",&molecules_container_t::get_interesting_places)
    .function("difference_map_peaks",&molecules_container_t::difference_map_peaks)
    .function("pepflips_using_difference_map",&molecules_container_t::pepflips_using_difference_map)
    .function("add_waters",&molecules_container_t::add_waters)
    .function("set_add_waters_water_to_protein_distance_lim_min",&molecules_container_t::set_add_waters_water_to_protein_distance_lim_min)
    .function("set_add_waters_water_to_protein_distance_lim_max",&molecules_container_t::set_add_waters_water_to_protein_distance_lim_max)
    .function("ramachandran_analysis",&molecules_container_t::ramachandran_analysis)
    .function("density_correlation_analysis",&molecules_container_t::density_correlation_analysis)
    .function("rotamer_analysis",&molecules_container_t::rotamer_analysis)
    .function("associate_data_mtz_file_with_map",&molecules_container_t::associate_data_mtz_file_with_map)
    .function("connect_updating_maps",&molecules_container_t::connect_updating_maps)
    .function("get_diff_diff_map_peaks", &molecules_container_t::get_diff_diff_map_peaks)
    .function("export_chemical_features_as_gltf", &molecules_container_t::export_chemical_features_as_gltf)
    .function("export_molecular_representation_as_gltf", &molecules_container_t::export_molecular_representation_as_gltf)
    .function("export_model_molecule_as_gltf", &molecules_container_t::export_model_molecule_as_gltf)
    .function("export_map_molecule_as_gltf", &molecules_container_t::export_map_molecule_as_gltf)
    .function("residues_with_missing_atoms",&molecules_container_t::residues_with_missing_atoms)
    .function("ramachandran_validation",&molecules_container_t::ramachandran_validation)
    .function("merge_molecules", select_overload<std::pair<int, std::vector<merge_molecule_results_info_t> >(int,const std::string &)>(&molecules_container_t::merge_molecules))
    .function("get_single_letter_codes_for_chain",&molecules_container_t::get_single_letter_codes_for_chain)
    .function("get_r_factor_stats",&molecules_container_t::get_r_factor_stats)
    .function("get_colour_rules",&molecules_container_t::get_colour_rules)
    .function("mmrrcc",&molecules_container_t::mmrrcc)
    .function("auto_read_mtz",&molecules_container_t::auto_read_mtz)
    .function("SSM_superpose",&molecules_container_t::SSM_superpose)
    .function("add_to_non_drawn_bonds",&molecules_container_t::add_to_non_drawn_bonds)
    .function("clear_non_drawn_bonds",&molecules_container_t::clear_non_drawn_bonds)
    .function("file_name_to_string",&molecules_container_t::file_name_to_string)
    .function("replace_molecule_by_model_from_file",&molecules_container_t::replace_molecule_by_model_from_file)
    .function("replace_residue",&molecules_container_t::replace_residue)
    .function("replace_map_by_mtz_from_file",&molecules_container_t::replace_map_by_mtz_from_file)
    .function("replace_fragment",&molecules_container_t::replace_fragment)
    .function("sharpen_blur_map",&molecules_container_t::sharpen_blur_map)
    .function("flip_hand",&molecules_container_t::flip_hand)
    .function("mask_map_by_atom_selection",&molecules_container_t::mask_map_by_atom_selection)
    .function("generate_self_restraints",&molecules_container_t::generate_self_restraints)
    .function("generate_chain_self_restraints",&molecules_container_t::generate_chain_self_restraints)
    .function("generate_local_self_restraints",&molecules_container_t::generate_local_self_restraints)
    .function("clear_extra_restraints",&molecules_container_t::clear_extra_restraints)
    .function("get_extra_restraints_mesh",&molecules_container_t::get_extra_restraints_mesh)
    .function("unmodelled_blobs",&molecules_container_t::unmodelled_blobs)
    .function("get_map_molecule_centre",&molecules_container_t::get_map_molecule_centre)
    .function("get_cell",&molecules_container_t::get_cell)
    .function("make_masked_maps_split_by_chain",&molecules_container_t::make_masked_maps_split_by_chain)
    .function("fit_to_map_by_random_jiggle_with_blur_using_cid",&molecules_container_t::fit_to_map_by_random_jiggle_with_blur_using_cid)
    .function("get_map_contours_mesh_using_other_map_for_colours",&molecules_container_t::get_map_contours_mesh_using_other_map_for_colours)
    .function("set_refinement_geman_mcclure_alpha",&molecules_container_t::set_refinement_geman_mcclure_alpha)
    .function("get_geman_mcclure_alpha",&molecules_container_t::get_geman_mcclure_alpha)
    .function("get_map_histogram",&molecules_container_t::get_map_histogram)
    .function("get_map_vertices_histogram",&molecules_container_t::get_map_vertices_histogram)
    .function("sharpen_blur_map_with_resample",&molecules_container_t::sharpen_blur_map_with_resample)
    .function("find_water_baddies",&molecules_container_t::find_water_baddies)
    .function("get_gphl_chem_comp_info",&molecules_container_t::get_gphl_chem_comp_info)
    .function("get_map_section_texture", &molecules_container_t::get_map_section_texture)
    .function("get_rdkit_mol_pickle_base64", &molecules_container_t::get_rdkit_mol_pickle_base64)
    .function("get_q_score", &molecules_container_t::get_q_score)
    .function("get_q_score_for_cid", &molecules_container_t::get_q_score_for_cid)
    .function("get_acedrg_atom_types_for_ligand", &molecules_container_t::get_acedrg_atom_types_for_ligand)
    .function("dictionary_atom_name_map", &molecules_container_t::dictionary_atom_name_map)
    .function("transform_map_using_lsq_matrix", &molecules_container_t::transform_map_using_lsq_matrix)
    .function("get_SMILES_for_residue_type", &molecules_container_t::get_SMILES_for_residue_type)
    .function("set_occupancy", &molecules_container_t::set_occupancy)
    .function("read_small_molecule_cif", &molecules_container_t::read_small_molecule_cif)
    .property("use_gemmi", &molecules_container_t::use_gemmi)
    ;
    class_<molecules_container_js, base<molecules_container_t>>("molecules_container_js")
    .constructor<bool>()
    .function("get_validation",&molecules_container_js::get_validation)
    .function("writePDBASCII",&molecules_container_js::writePDBASCII)
    .function("writeCIFASCII",&molecules_container_js::writeCIFASCII)
    .function("writeCCP4Map",&molecules_container_js::writeCCP4Map)
    .function("get_map_data_resolution",&molecules_container_js::get_map_data_resolution)
    .function("get_map_cell",&molecules_container_js::get_map_cell)
    .function("get_map_spacegroup",&molecules_container_js::get_map_spacegroup)
    .function("get_map_bounding_sphere",&molecules_container_js::get_map_bounding_sphere)
    .function("count_simple_mesh_vertices",&molecules_container_js::count_simple_mesh_vertices)
    .function("go_to_blob_array",&molecules_container_js::go_to_blob_array)
    .function("add",&molecules_container_js::add)
    .function("getFloats",&molecules_container_js::getFloats)
    .function("get_symmetry_with_matrices",&molecules_container_js::get_symmetry_with_matrices)
    .function("get_neighbours_cid",&molecules_container_js::get_neighbours_cid)
    .function("make_exportable_environment_bond_box",&molecules_container_js::make_exportable_environment_bond_box)
    .function("DrawGlycoBlocks",&molecules_container_js::DrawGlycoBlocks)
    .function("privateer_validate",&molecules_container_js::privateer_validate)
    .function("GetSecondaryStructure",&molecules_container_js::GetSecondaryStructure)
    .function("DrawMoorhenMetaBalls",&molecules_container_js::DrawMoorhenMetaBalls)
    .function("model_has_glycans",&molecules_container_js::model_has_glycans)
    .function("get_molecule_atoms", &molecules_container_js::get_molecule_atoms)
    .function("read_coords_string", &molecules_container_js::read_coords_string)
    .function("smiles_to_pdb", &molecules_container_js::smiles_to_pdb)
    .function("mol_text_to_pdb", &molecules_container_js::mol_text_to_pdb)
    .function("replace_molecule_by_model_from_string", &molecules_container_js::replace_molecule_by_model_from_string)
    .function("read_dictionary_string", &molecules_container_js::read_dictionary_string)
    .function("slicendice_slice", &molecules_container_js::slicendice_slice)
    .function("molecule_to_mmCIF_string_with_gemmi", &molecules_container_js::molecule_to_mmCIF_string_with_gemmi)
    .function("export_molecular_representation_as_obj", &molecules_container_js::export_molecular_representation_as_obj)
    .function("export_model_molecule_as_obj", &molecules_container_js::export_model_molecule_as_obj)
    .function("export_map_molecule_as_obj", &molecules_container_js::export_map_molecule_as_obj)
    .function("export_molecular_representation_as_3mf_xml", &molecules_container_js::export_molecular_representation_as_3mf_xml)
    .function("export_model_molecule_as_3mf_xml", &molecules_container_js::export_model_molecule_as_3mf_xml)
    .function("export_map_molecule_as_3mf_xml", &molecules_container_js::export_map_molecule_as_3mf_xml)
    .function("export_metaballs_as_obj", &molecules_container_js::export_metaballs_as_obj)
    .function("export_metaballs_as_gltf", &molecules_container_js::export_metaballs_as_gltf)
    .function("export_metaballs_as_3mf_xml", &molecules_container_js::export_metaballs_as_3mf_xml)
    ;
}
