# UBUNTU SETUP
FROM ubuntu:focal AS build
ENV TZ=Europe/London
ARG DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]
RUN apt-get update
RUN apt-get -y install autoconf autotools-dev libtool bzr git curl cmake gcc clang python3-dev libz-dev

# INSTALL EMSCRIPTEN
RUN mkdir -p /opt/
WORKDIR /opt/
RUN  git clone https://github.com/emscripten-core/emsdk.git
RUN /opt/emsdk/emsdk install latest
RUN /opt/emsdk/emsdk activate latest

# CLONE CCP4 WEB-ASSEMBLY AND DOWNLOAD SOURCES
RUN  git clone https://github.com/stuartjamesmcnicholas/CCP4-Web-Assembly.git ccp4_wasm
WORKDIR /opt/ccp4_wasm/
RUN /opt/ccp4_wasm/get_sources

# INSTALL
RUN source /opt/emsdk/emsdk_env.sh && emcmake cmake .
RUN source /opt/emsdk/emsdk_env.sh && emmake make
RUN source /opt/emsdk/emsdk_env.sh && make install

# INSTALL WEBPACK
COPY /opt/ccp4_wasm/react-app/src /opt/ccp4_wasm/baby-gru/src/WebGL 
WORKDIR /opt/ccp4_wasm/baby-gru/
RUN npm install

# START BABY-GRU AND EXPOSE PORT
CMD ["npm", "start"]
EXPOSE 3000

