name: Publish dev docs

on:
  push:
    # Only build dev docs based on the branch for the latest release...
    branches:
      - v0.22
      - v0.23
      - v0.24
      - v0.25
      - v0.26
      - v0.27
      - v0.28
      - v0.29
      - v0.30
      - v0.31
      - v0.32
      - v1.0
      - v1.1
      - v1.2
      - v1.3
      - v1.4
      - v1.5
      - v1.6
      - v1.7
      - v1.8
      - v1.9
      - v1.10
      - v1.11

jobs:
  publish_dev_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node.js v24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Update mirrors
        working-directory: /home/runner/work/Moorhen/
        run: sudo apt-get update -y

      - name: Install dependencies 
        working-directory: /home/runner/work/Moorhen/
        run: |    
          sudo apt-get install -y npm

      - name: Create mock version file
        working-directory: /home/runner/work/Moorhen/       
        run: |    
          echo "export const version = 0.1" > /home/runner/work/Moorhen/Moorhen/baby-gru/src/version.js

      - name: npm install
        working-directory: /home/runner/work/Moorhen/Moorhen/baby-gru
        run: npm install

      - name: compile jsDocs
        working-directory: /home/runner/work/Moorhen/Moorhen/baby-gru
        run: |
          npm install --force better-docs
          npx jsdoc -c jsdoc.json    
          
      - name: Publishing on Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /home/runner/work/Moorhen/Moorhen/baby-gru/docs
